git-add -i: update removed path correctly.
Earlier, when a path that was removed from the working tree was
chosen for update subcommand, you got an error like this:

    error: git-resolve.sh: does not exist and --remove not passed
    fatal: Unable to process file git-resolve.sh

Signed-off-by: Junio C Hamano <junkio@cox.net>